name: neighborhood_market
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^3.12.0
  injectable: ^2.5.0
  get_it: ^8.0.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  go_router: ^14.6.2
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  mask_text_input_formatter: ^2.9.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  pull_to_refresh: ^2.0.0
  carousel_slider: ^5.0.0
  rxdart: ^0.28.0
  event_bus: ^2.0.1
  onesignal_flutter: ^5.2.8
  flutter_stripe: ^11.5.0
  flutter_icon_snackbar: ^1.2.1
  flutter_dotenv: ^5.2.1
  photo_view: ^0.15.0
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  firebase_dynamic_links: ^6.1.3
  # app_links: ^6.4.0
  flutter_timezone: ^4.1.0
  firebase_remote_config: ^5.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_padding.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_padding.png"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  
  
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_foreground.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/categories/
    - assets/json/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-BlackItalic.ttf
          weight: 900
          style: italic
